title: Pop Culture Parade
author: Chris Manning
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  All things Schitt's Creek, Star Wars, Nintendo, and any and all
  other pop culture topics that I care to write about. I'm a
  voracious consumer of pop culture, so to list all the things
  would take far too much space.

# social links
twitter_username: chrismanning # DO NOT include the @ character, or else the build will fail!
github_username:  LMNOPx # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
