title: Pop Culture Parade
author: Chris Manning
email: chris@chrismanningdigital.com
description: > 
  All things Schitt's Creek, Star Wars, Nintendo, and any and all
  other pop culture topics that I care to write about. I'm a
  voracious consumer of pop culture, so to list all the things
  would take far too much space.

# social links
twitter_username: chrismanning
github_username:  LMNOPx

show_excerpts: true
theme: minima
